services:
  ros:
    image: my-local/altem_iot:latest
    container_name: f170_ros
    environment:
      DISPLAY: ${DISPLAY}
      F170_TB_MQTT_ACCESS_TOKEN: ${F170_TB_MQTT_ACCESS_TOKEN}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host
    stdin_open: true
    tty: true
